### ISSUE TITLE
Readme.md of this repo summarizing internship goals

### ISSUE THREAD

**Issue by marekgluza** [csookim/qibo_cskim#14]
Following #12 I suggest to write a README.md for this repo summarizing with histogram plots the ongoing challenges

Just show the results that lead to the statements, you can link to the notebooks for details:

### #3 Qibo vs Qiskit SABRE implementation comparison
 - For QFT(10), the average number of CZ gates is similar, but the minimum number of CZ gates is smaller when using Qiskit SABRE.
- For random CZ circuits, both the average and minimum number of CZ gates are smaller when using Qiskit SABRE.
- Qiskit shows more fluctuation.
- This indicates that Qiskit SABRE has the potential to generate routings with fewer CZ gates.
- Qibo SABRE needs optimization.

### #4 Selection of router algorithms
- QFT(5) + Cycle: Shortestpath has fewer CNOTs than SABRE.
- QFT(5) + Star: the averages are the same.
- Random circuit: the average and fluctuation are similar.
- Shortestpath has the potential to generate routings with fewer CZ gates.

### #5 Placer strategies for IQM5 and 20

- There are significant fluctuations in transpiling with each placer. 
- On average, Subgraph Isomorphism generates the smallest number of CZ gates.

### #8 Transpiler strategies in presence of noise

- In a noisy simulation of a circuit with random 5 CZs, the complete graph has the lowest error rate.
- In a noisy simulation with QFT, the error rate cannot be easily shown due to the complexity of the QFT circuit.

**Comment by csookim** [comment]
- [ ] Write a README file
- [ ] Introduce challenges with histograms
- [ ] Link notebooks where further details can be found
