### ISSUE TITLE
Reporting timeline

### ISSUE THREAD

**Issue by marekgluza** [csookim/qibo_cskim#15]
Stefano will be at CQT on the 15th
- [x] @csookim please be ready to show the Readme file from #14 

On the 24th at 2pm at CQT there will be the NQCH meeting in person. Stefano will join remotely.
- [x] @csookim you will be asked to summarize your activities, we will discuss this with Stefano on 15th but you can in general start preparing slides.com (see e.g.  https://slides.com/marekgluza/quantum_processing_qibo for a showcasing what can be fairly easily done with their UI)

**Comment by csookim** [comment]
- [ ] Remind about the NQCH presentation
