### ISSUE TITLE
Fix numerical instability issues in cnot_decomposition @ qibo

### ISSUE THREAD

**Issue by marekgluza** [csookim/qibo_cskim#17]
- [x] The goal is to learn the workflow and integrate an existing solution and complete a first PR contribution to qibo after review
The implementation of `cnot_decomposition` seems unstable

Task 1: document bug by a bug-issue in qibo main repo showing for which matrix the current CK decomposition is unstable
- [x] try running this on the unitary $X\otimes X + Z\otimes 1$ which should give an error 
from qibo.transpiler.unitary_decompositions import two_qubit_decomposition
- [x] run the same example on the KAK PR file from Ingo https://github.com/qiboteam/qibo/pull/1384
Task 2:
- [x] Open question: do we have any instance where Ingo's version breaks?
Task 3:
- refactor Ingo's code
- [x] write a test function (probably the one from Ingo) and add to an appropriate test_transpiler*.py file https://github.com/qiboteam/qibo/blob/qdp/tests/test_transpiler_unitary_decompositions.py

**Comment by csookim** [comment]
@marekgluza 

While running Ingo's code, should the unitary XX+ZI generate an error?

**Comment by marekgluza** [comment]
No it should work. And currently tensorflow with the current qibo version
actually gives a correct output.

Actually right now we don't have anymore an example that remains unstable
because maybe another bug got fixed.

On the other hand the current solution runs a round heuristic and there
were a lot of issues previously so implementing an option to switch to KAK
is still worthwhile

**Comment by csookim** [comment]
Ok. @marekgluza Could you send me the paper about decomposition that you are planning to implement?

I would like to know where KAK should be placed.

**Comment by marekgluza** [comment]
In my opinion this is the most self-contained and focused on our subject is this
https://arxiv.org/abs/quant-ph/0209120
see eq 16

> you are planning to implement
We have the implementation from Ingo, we only need to incorporate it into qibo.

But the task is not to understand how this works but rather to pass through the qibo review workflow given the existing functions. For this only the setting should be clear - for any 2q unitary U there are two unitaries K,K' which are only single qubit rotations such that U = K x Heinsenberg x K'
Finding the parametrization of Heisenberg has been unstable before even though the rounding fix seems to stabilize it for now.
In order to prevent more issues like that we want to catch the errors
https://github.com/qiboteam/qibo/blob/3d25e4f2e1ac72d3b601179dbadf14eac9bf8e8e/src/qibo/transpiler/unitary_decompositions.py#L124-L128
and try KAK from Ingo.
(I think the new KAK will be systematically better but for the first round of peer review I would just take KAK as the troubleshooting routine)

- Jeongrak learned KAK from d'Allesandro's text book
which I think is similar to
https://arxiv.org/pdf/quant-ph/0006114

- This might have some useful discussions too 
https://github.com/qiskit-advocate/qamp-spring-23/issues/33#issuecomment-1583713684

**Comment by csookim** [comment]
Thanks! I will first refactor the KAK code and make a PR. I just want to know where it will be used.

**Comment by marekgluza** [comment]
> know where it will be used

- For the transpiler, we will use the blocks function later. The idea is that you find blocks in the circuit that pertain to 2 qubits and if they involve more than 4 qubits then we can recompile the circuit. Note, that the present method is smart and can sometimes recompile a 2 qubit block by 2 cnots (I learned this only yesterday)

- another application that is nice is that you write a 2 local qubit model and then the circuit method will consist of 2 body gates. You can decompose that circuit into cnots. This is an example of circuits that arise in adiabatic qc implemented by Hamiltonian simulation
```python
import qibo
from qibo.symbols import *

from qibo.hamiltonians import SymbolicHamiltonian
from qibo.transpiler.unitary_decompositions import two_qubit_decomposition

nqubits = 10
delta = 0.5
hamiltonian = SymbolicHamiltonian(
sum(
    [
        X(j) * X(j + 1)
        + Y(j) * Y(j + 1)
        + delta * Z(j) * Z(j + 1)
        for j in range(nqubits - 1)
    ]
    + [
        X(nqubits - 1) * X(0)
        + Y(nqubits - 1) * Y(0)
        + delta * Z(nqubits - 1) * Z(0)
    ]
),
nqubits=nqubits,
)

for g in hamiltonian.circuit(0.1).queue:
    two_qubit_decomposition(0,1,g.matrix())`
